Use a separate build mode to the LLVM build mode

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -654,6 +654,7 @@ target_os
 LLVM_VERSION_MAJOR
 LLVM_VERSION_MINOR
 LLVM_IS_RELEASE
+LLVM_BUILD_MODE
 KLEE_UCLIBC
 ENABLE_UCLIBC
 ENABLE_POSIX_RUNTIME
@@ -1276,6 +1277,8 @@ Optional Packages:
   --with-llvmsrc          Location of LLVM Source Code
   --with-llvmobj          Location of LLVM Object Code
   --with-llvm             Location of LLVM Source and Object code
+  --with-llvm-build-mode  LLVM build mode (e.g. Debug or Release, default
+                          autodetect)
   --with-uclibc           Enable use of the klee uclibc at the given path
   --with-runtime          Select build configuration for runtime libraries
                           (default Release)
@@ -2069,6 +2072,43 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 LLVM_IS_RELEASE=$llvm_is_release
+
+
+
+# Check whether --with-llvm-build-mode was given.
+if test "${with_llvm_build_mode+set}" = set; then
+  withval=$with_llvm_build_mode;
+else
+  with_llvm_build_mode=check
+fi
+
+
+{ echo "$as_me:$LINENO: checking llvm build mode" >&5
+echo $ECHO_N "checking llvm build mode... $ECHO_C" >&6; }
+
+if test X${with_llvm_build_mode} = Xcheck ; then
+  llvm_configs="`echo $llvm_obj/*/bin/llvm-config`"
+    if test -x "$llvm_configs" ; then
+    llvm_build_mode="`$llvm_configs --build-mode`"
+  else
+    { { echo "$as_me:$LINENO: error: Could not autodetect build mode" >&5
+echo "$as_me: error: Could not autodetect build mode" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+else
+  llvm_configs="`echo $llvm_obj/*/bin/llvm-config`"
+  if test -x "$llvm_obj/$with_llvm_build_mode/bin/llvm-config" ; then
+    llvm_build_mode=$with_llvm_build_mode
+  else
+    { { echo "$as_me:$LINENO: error: Invalid build mode: $llvm_build_mode" >&5
+echo "$as_me: error: Invalid build mode: $llvm_build_mode" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
+
+{ echo "$as_me:$LINENO: result: $llvm_build_mode" >&5
+echo "${ECHO_T}$llvm_build_mode" >&6; }
+LLVM_BUILD_MODE=$llvm_build_mode
 
 
 
@@ -6006,6 +6046,7 @@ target_os!$target_os$ac_delim
 LLVM_VERSION_MAJOR!$LLVM_VERSION_MAJOR$ac_delim
 LLVM_VERSION_MINOR!$LLVM_VERSION_MINOR$ac_delim
 LLVM_IS_RELEASE!$LLVM_IS_RELEASE$ac_delim
+LLVM_BUILD_MODE!$LLVM_BUILD_MODE$ac_delim
 KLEE_UCLIBC!$KLEE_UCLIBC$ac_delim
 ENABLE_UCLIBC!$ENABLE_UCLIBC$ac_delim
 ENABLE_POSIX_RUNTIME!$ENABLE_POSIX_RUNTIME$ac_delim
@@ -6033,7 +6074,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 79; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 80; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
